# Generated by Django 3.1.4 on 2021-07-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialize', '0008_auto_20210706_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialize',
            name='contributor',
            field=models.ManyToManyField(blank=True, to='socialize.Contributor'),
        ),
    ]
